backend:
  name: github
  branch: master
  repo: erezrokah/netlify-cms-reproductions

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
collections:
  - name: contentpages
    label: Content pages
    files:
      - label: Homepage
        name: homepage
        file: src/pages/contentpages/homepage.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: url
            name: url
            widget: hidden
            default: /
          - label: Body
            name: body
            widget: markdown
