backend:
  name: github
  branch: master
  repo: erezrokah/netlify-cms-reproductions

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
collections:
  - name: 'cards'
    label: 'Frontpage'
    label_singular: 'Card'
    folder: '_content/_cards'
    create: true
    fields:
      - label: Title
        name: title
        widget: string
        hint: Een herkenbare titel met enkele kernwoorden.

      - label: Order
        name: order
        widget: number
        default: 1
        valueType: 'int'
        min: 1
        max: 99
        hint: De plaats van dit item op de frontpage.

      - label: Image
        name: image
        widget: image

      - label: Body
        name: body
        widget: markdown
