backend:
  name: git-gateway
  branch: netlify_cms/issue_1745

media_folder: static/media
public_folder: /media
local_backend: true
collections:
  - name: things
    label: Things
    label_singular: thing
    folder: things
    create: true
    slug: '{{id}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Id
        name: id
        widget: string
      - label: Publication Date
        name: publicationDate
        default: ''
        required: false
        widget: datetime
