backend:
  name: github
  branch: netlify_cms/issue_3470
  repo: erezrokah/netlify-cms-reproductions

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
collections:
  - name: 'sections-en'
    label: 'Sections - EN'
    folder: 'hugosite/content/en/'
    create: true
    slug: '_index'
    path: '../{{language}}/{{section}}/{{slug}}'
    media_folder: '../../../static/img/'
    public_folder: 'img'
