backend:
  name: github
  branch: netlify_cms/issue_3128
  repo: erezrokah/netlify-cms-reproductions
  site_domain: quirky-bassi-7f760a.netlify.com

public_folder: '/src/images/'
media_folder: '/src/images/'
media_library:
  name: cloudinary
  config:
    cloud_name: erezro
    api_key: '591979259993767'

collections:
  - label: 'Projects' # Used in the UI
    name: 'projects' # Used in routes, e.g., /admin/collections/blog
    label_singular: 'Project'
    folder: 'src/data/projects' # The path to the file where projects are defined
    media_folder: 'images' # Should save images in same directory as the project, to make referencing easier
    create: true
    extension: json
    format: json
    fields: # The fields for each document, usually in front matter
      - {
          label: 'Project Name',
          name: 'title',
          widget: 'string',
          hint: 'A project name used for files and folders',
          pattern:
            ['^[\w\-]+$', 'Accepted characters are alphanumeric, _, and -.'],
        }
      - {
          label: 'Image',
          name: 'image',
          widget: 'image',
          allow_multiple: false,
        }
      - label: 'Gallery'
        name: 'galleryImages'
        widget: 'list'
        field:
          {
            label: 'Image',
            name: 'image',
            widget: 'image',
            allow_multiple: true,
          }
