backend:
  name: github
  branch: netlify_cms/single_file_media_folder
  repo: erezrokah/netlify-cms-reproductions

media_folder: static/media
public_folder: /media

collections:
  - label: 'Contact'
    name: 'contact'
    file: 'content/contact/index.md' # We're writing to a directory
    media_folder: '' # Wish to store uploads in `content/contact/` as well
    public_folder: '' # And serve from there
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
