backend:
  name: github
  branch: netlify_cms/issue_54
  repo: erezrokah/netlify-cms-reproductions

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
local_backend: true
collections:
  - name: posts
    label: Posts
    label_singular: 'Post'
    folder: content/posts
    create: true
    sortableFields: ['title', 'date']
    summary: '{{title}} - {{date}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime

  - name: pages
    label: Pages
    label_singular: 'Page'
    folder: content/pages
    create: true
    sortableFields: ['title', 'date']
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
