backend:
  name: github
  branch: netlify_cms/issue_3810
  repo: erezrokah/netlify-cms-reproductions

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
local_backend: true

collections:
  - label: lookups
    name: lookups
    files:
      - label: cities
        name: cities
        file: data/cities.json
        fields:
          - label: cities
            label_singular: city
            name: cities
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: id
                name: id
                widget: hidden
  - label: Folder Collection
    name: folder_collection
    folder: content/folder_collection
    create: true
    identifier_field: id
    slug: '{{city}}'
    summary: '{{city}}'
    editor:
      preview: false
    fields:
      - label: id
        name: id
        widget: ncw-id

      - label: City
        name: city
        widget: relation
        collection: lookups
        file: cities
        searchFields: ['cities.*.name']
        displayFields: ['cities.*.name']
        valueField: cities.*.name
