backend:
  name: github
  branch: netlify_cms/issue_3950
  repo: erezrokah/netlify-cms-reproductions

media_folder: static/media
public_folder: /media
local_backend: true
collections:
  - name: en_posts
    label: English Posts
    label_singular: 'Post'
    folder: content/posts
    create: true
    slug: '{{slug}}-{{lang}}'
    filter:
      field: lang
      value: en
    fields:
      - label: Title
        name: title
        widget: string
      - label: Language
        name: lang
        widget: select
        options: ['en', 'es']

  - name: es_posts
    label: Spanish Posts
    label_singular: 'Post'
    folder: content/posts
    create: true
    slug: '{{slug}}-{{lang}}'
    filter:
      field: lang
      value: es
    fields:
      - label: Title
        name: title
        widget: string
      - label: Language
        name: lang
        widget: select
        options: ['en', 'es']
