backend:
  name: github
  branch: netlify_cms/fix_open_authoring_migration
  repo: erezrokah/netlify-cms-reproductions
  open_authoring: true

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
local_backend: true
collections:
  - name: posts
    label: Posts
    label_singular: 'Post'
    folder: content/posts
    create: true
    fields:
      - label: Title
        name: title
        widget: string
