backend:
  name: test-repo
load_config_file: 'false'
display_url: https://netlify-cms-react-example.netlify.com
media_folder: public/assets/uploads
public_folder: '/assets/uploads'
collections:
  - name: posts
    label: Posts
    delete: false
    editor:
      preview: false
    files:
      - name: posts
        label: Posts
        file: _data/posts.yml
        description: Author descriptions
        fields:
          - name: sectionsString
            label: Sections String (no issue)
            label_singular: Section
            widget: list
            fields:
              - label: String
                name: string
                widget: string
          - name: sectionsMd
            label: Sections Markdown (has issue)
            label_singular: Section
            widget: list
            fields:
              - label: Markdown
                name: markdown
                widget: markdown
                minimal: true
