backend:
  name: github
  branch: netlify_cms/issue_3654
  repo: erezrokah/netlify-cms-reproductions

media_folder: /static/uploads/
public_folder: /uploads
collections:
  - name: posts
    label: Posts
    label_singular: 'Post'
    folder: src/content/posts
    create: true
    public_folder: '../../../static/uploads/'
    fields:
      - label: Title
        name: title
        widget: string
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
      - label: Body
        name: body
        widget: markdown
