backend:
  name: github
  branch: netlify_cms/issue_3054
  repo: erezrokah/netlify-cms-reproductions

publish_mode: editorial_workflow
media_folder: static/images
public_folder: static/images

collections:
  - name: pages
    label: Pages
    label_singular: 'Page'
    folder: content
    path: '{{language}}/{{categories[0]}}/{{title}}'
    media_folder: '../../../{{media_folder}}/{{categories[0]}}/{{filename}}'
    public_folder: '/{{public_folder}}/{{categories[0]}}/{{filename}}'
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Language
        name: language
        widget: select
        options:
          - { label: 'English', value: 'en' }
          - { label: 'Chinese', value: 'zh' }
        default: en
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Categories
        name: categories
        widget: list
      - label: Body
        name: body
        widget: markdown
