backend:
  name: github
  branch: master
  repo: erezrokah/netlify-cms-reproductions

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
collections:
  - name: posts
    label: Posts
    label_singular: 'Post'
    folder: content/posts
    create: true
    fields:
      - label: Template
        name: template
        widget: hidden
        default: post
      - label: Title
        name: title
        widget: string
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        default: ['news']
      - label: 'Gallery'
        name: 'galleryImages'
        widget: 'list'
        field: { label: Image, name: image, widget: image }
      - label: 'Testimonials'
        name: 'testimonials'
        widget: 'list'
        fields:
          - {
              label: Quote,
              name: quote,
              widget: string,
              default: 'Everything is awesome!',
            }
          - label: Author
            name: author
            widget: object
            fields:
              - { label: Name, name: name, widget: string, default: 'Emmet' }
              - {
                  label: Avatar,
                  name: avatar,
                  widget: image,
                  default: '/img/emmet.jpg',
                }
