backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
local_backend: true
collections:
  - name: files
    label: Files
    label_singular: 'File'
    files:
      - file: 'src/pages/board/index.md'
        label: 'Board Page'
        name: 'board'
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: File,
              name: file,
              media_folder: '/static/board',
              widget: file,
            }
