backend:
  name: github
  branch: netlify_cms/issue_3436
  repo: erezrokah/netlify-cms-reproductions

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
local_backend: true

collections:
  - name: leadership
    label: Leadership
    folder: content/leadership
    create: true
    media_folder: ../../static/images/leadership
    public_folder: /images/leadership

    fields:
      - label: Title
        name: title
        widget: string
      - label: 'Profile Image'
        name: 'imgSrc'
        widget: 'image'
        pattern: [
            '^blah_[a-z]+-[a-z]+\.(jpg|jpeg|png|gif|bmp)$',
            'Must match the format: blah_{firstname}-{lastname}.{format}
            without brackets and have one of the following extensions (jpg|jpeg|png|gif|bmp)',
          ]
