backend:
  name: github
  branch: netlify_cms/issue_716
  repo: erezrokah/netlify-cms-reproductions

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
local_backend: true
i18n: { structure: multiple_folders, locales: [en, de, fr] }
collections:
  - name: locale_folders
    label: Locale Folders
    folder: content/locale_folders
    create: true
    i18n: true
    fields:
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Date
        name: date
        widget: datetime
        i18n: 'duplicate'
      - label: Body
        name: body
        widget: markdown
  - name: locale_file_extensions
    label: Locale File Extensions
    folder: content/locale_file_extensions
    create: true
    i18n: { structure: multiple_files }
    fields:
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Date
        name: date
        widget: datetime
        i18n: 'duplicate'
      - label: Body
        name: body
        widget: markdown
  - name: single_file
    label: Single File
    folder: content/single_file
    create: true
    i18n: { structure: single_file }
    fields:
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Date
        name: date
        widget: datetime
        i18n: 'duplicate'
      - label: Body
        name: body
        widget: markdown
