backend:
  name: github
  branch: netlify_cms/pr_3219
  repo: erezrokah/netlify-cms-reproductions

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
collections:
  - name: 'posts'
    identifier_field: 'en.title'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'src/pages/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: English
        name: en
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - label: Spanish
        name: es
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

      - label: Title
        name: title
