backend:
  name: git-gateway
  branch: master

local_backend: true
media_folder: static/media
public_folder: /media
collections:
  - name: posts
    label: Posts
    label_singular: 'Post'
    folder: content/posts
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Relation
        name: relation
        widget: relation
        collection: files
        valueField: categories.*.id
        searchFields: [categories.*.name]
        displayFields: [categories.*.name, categories.*.id]
        file: categories
  - name: files
    label: Files
    label_singular: 'File'
    files:
      - label: Categories
        name: categories
        file: _data/_cats.json
        fields:
          - label: Categories
            name: categories
            widget: list
            allow_add: true
            fields:
              - label: Name
                name: name
                widget: string
              - label: Id
                name: id
                widget: string

      - label: Tags
        name: tags
        file: _data/_tags.json
        fields:
          - label: Tags
            name: tags
            widget: list
            allow_add: true
            fields:
              - label: Name
                name: name
                widget: string
              - label: Id
                name: id
                widget: string
