backend:
  name: github
  repo: erezrokah/netlify-cms-reproductions
  branch: netlify_cms/issue_3227

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
collections:
  - name: pages
    label: Pages
    label_singular: 'Page'
    folder: content
    create: true
    nested: { depth: 100 } # accepts an optional summary template
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
