backend:
  name: github
  branch: netlify_cms/issue_3235
  repo: erezrokah/netlify-cms-reproductions

local_backend: true

media_folder: /static/img
collections:
  - name: general
    media_folder: '{{media_folder}}/general/'
    files:
      - name: partners
        fields:
          - name: featured_image
            widget: image
            media_folder: '{{media_folder}}/partners/'
      - name: customers
        media_folder: '{{media_folder}}/customers/'
        fields:
          - name: main_image
            widget: image
          - name: logo
            widget: image
            media_folder: '{{media_folder}}/logos/'
