backend:
  name: github
  branch: netlify_cms/issue_565
  repo: erezrokah/netlify-cms-reproductions

publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
local_backend: true
collections:
  - label: 'structure'
    name: structure
    folder: 'structure'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'structure'
        name: structure
        widget: 'list'
        fields:
          - {
              label: 'type',
              name: 'type',
              widget: 'select',
              default: '',
              options:
                ['copy', 'divider', 'image', 'infographic', 'productCircle'],
            }
          - label: content
            name: content
            widget: object
            fields:
              - {
                  label: 'text',
                  name: 'text',
                  widget: 'markdown',
                  conditions:
                    [
                      {
                        fieldPath: 'structure.*.type',
                        oneOf:
                          ['divider', 'productCircle', infographic, image, ''],
                      },
                    ],
                }
              - {
                  label: 'src',
                  name: 'src',
                  widget: 'image',
                  conditions:
                    [
                      {
                        fieldPath: 'structure.*.type',
                        oneOf: ['divider', 'productCircle', copy, ''],
                      },
                    ],
                }
              - {
                  label: 'overlay',
                  name: 'overlay',
                  widget: 'image',
                  conditions:
                    [
                      {
                        fieldPath: 'structure.*.type',
                        oneOf: ['divider', 'productCircle', copy, image, ''],
                      },
                    ],
                }
