backend:
  name: git-gateway
  branch: netlify_cms/issue_slack_preview_t_not_defined
media_folder: static/img
public_folder: /img
site_url: https://my.site.url
collections:
  - name: 'news'
    label: 'News'
    format: 'json'
    folder: 'assets/content/news'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: news/{{slug}}
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
